title: My sample book
author: Casper
only_build_toc_files: true
exclude_patterns: [.github/*]
repository:
  url: https://github.com/casperdcl/test-jupyterbook
  branch: main
parse:
  myst_enable_extensions: # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
  # needs myst-parser>=0.19 <- https://github.com/executablebooks/MyST-NB/issues/530
  #- attrs_block
  #- attrs_inline
  - deflist
  - dollarmath
  - html_admonition
  - linkify
  - replacements
  - smartquotes
  - substitution
  - tasklist
sphinx:
  extra_extensions:
  - sphinxemoji.sphinxemoji
  - sphinx_last_updated_by_git
  - sphinx_subfigure
  config:
    myst_heading_anchors: 4
    jblatex_show_tocs: false
    bibtex_reference_style: label
bibtex_bibfiles: [references.bib] # citations
latex: # for PDF builds
  latex_documents:
    targetname: book.tex
execute:
  execute_notebooks: force  # re-exec on each build (https://jupyterbook.org/content/execute.html)
