title: My sample book
author: The Jupyter Book Community
latex:
  latex_documents:
    targetname: book.tex
#bibtex_bibfiles:
#  - references.bib
sphinx:
  config:
    myst_heading_anchors: 4
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)
